# noinspection SqlNoDataSourceInspectionForFile

DROP DATABASE IF EXISTS `ratpack03`;

CREATE DATABASE `ratpack03`;

USE `ratpack03`;

CREATE TABLE `USER` (
  ID           INT PRIMARY KEY AUTO_INCREMENT,
  `EMAIL`      VARCHAR(255),
  `FIRSTNAME`  VARCHAR(255),
  `LASTNAME`   VARCHAR(255),
  `ADDRESS1`   VARCHAR(255),
  `ADDRESS2`   VARCHAR(255),
  `CITY`       VARCHAR(255),
  `STATE`      VARCHAR(255),
  DATE_CREATED DATE,
  LAST_UPDATED DATE
);

INSERT INTO `USER` (EMAIL, FIRSTNAME, LASTNAME, ADDRESS1, ADDRESS2, CITY, STATE)
VALUES ('luke@gmail.com', 'Luke', 'Daily', '', '', 'Palo Alto', 'CA');
INSERT INTO `USER` (EMAIL, FIRSTNAME, LASTNAME, ADDRESS1, ADDRESS2, CITY, STATE)
VALUES ('rob@gmail.com', 'Rob', 'Fletch', '', '', 'Menlo Park', 'CA');
INSERT INTO `USER` (EMAIL, FIRSTNAME, LASTNAME, ADDRESS1, ADDRESS2, CITY, STATE)
VALUES ('dan@gmail.com', 'Dan', 'Woods', '101 Redwood Shores Parkway', '', 'Redwood City', 'CA');

CREATE TABLE `EVENT` (
  ID           INT PRIMARY KEY AUTO_INCREMENT,
  `TYPE`       VARCHAR(255),
  `DETAIL`     VARCHAR(255),
  DATE_CREATED DATE,
  LAST_UPDATED DATE
);

CREATE TABLE `METRIC` (
  ID           INT PRIMARY KEY AUTO_INCREMENT,
  `NAME`       VARCHAR(255),
  DATE_CREATED DATE,
  LAST_UPDATED DATE
);

CREATE TABLE `CHARITY` (
  ID           INT PRIMARY KEY AUTO_INCREMENT,
  `NAME`       VARCHAR(255),
  `EIN`        VARCHAR(255),
  DATE_CREATED DATE,
  LAST_UPDATED DATE
);