export const types = {
    RESET_EVENTS: 'RESET_EVENTS',
    APPEND_EVENTS: 'APPEND_EVENTS',

    RESET_ITEMS: 'RESET_ITEMS',
    APPEND_ITEMS: 'APPEND_ITEMS',

    SET_FORM: 'SET_FORM',
    SET_FORM_FIELD: 'SET_FORM_FIELD',
    CLEAR_FORM: 'CLEAR_FORM'
};
